In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer,KNNImputer

In [3]:
df=pd.read_csv('dataset/titanic.csv',usecols=['Age','Pclass','Fare','Survived'])
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [5]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Age       714 non-null    float64
 3   Fare      891 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [8]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [9]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [10]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [12]:
y_train

445    1
650    0
172    1
450    0
314    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 623, dtype: int64

# KNN Imputer

hyper parameter : n_neighbors=8,weights='distance'/'uniform'

In [32]:
knn=KNNImputer()
X_train_knn=knn.fit_transform(X_train)
X_test_knn=knn.transform(X_test)

In [33]:
X_test_knn

array([[  3.        ,  29.        ,  15.2458    ],
       [  2.        ,  31.        ,  10.5       ],
       [  3.        ,  20.        ,   7.925     ],
       [  2.        ,   6.        ,  33.        ],
       [  3.        ,  14.        ,  11.2417    ],
       [  1.        ,  26.        ,  78.85      ],
       [  3.        ,  28.5       ,   7.75      ],
       [  3.        ,  16.        ,  18.        ],
       [  3.        ,  16.        ,   7.75      ],
       [  1.        ,  19.        ,  26.2833    ],
       [  1.        ,  37.        ,  53.1       ],
       [  3.        ,  44.        ,   8.05      ],
       [  3.        ,  16.2       ,  25.4667    ],
       [  3.        ,  30.        ,   7.225     ],
       [  2.        ,  36.        ,  13.        ],
       [  1.        ,  16.        ,  39.4       ],
       [  1.        ,  42.        ,  52.5542    ],
       [  3.        ,  26.6       ,   7.8292    ],
       [  2.        ,  27.        ,  13.        ],
       [  1.        ,  47.        ,  52.        ],
       [  3.        ,  24.        ,   7.8958    ],
       [  1.        ,  34.        ,  26.55      ],
       [  3.        ,  19.        ,   7.8542    ],
       [  3.        ,  20.        ,   9.225     ],
       [  3.        ,  35.5       ,  14.5       ],
       [  3.        ,  10.        ,  27.9       ],
       [  1.        ,  40.        ,  27.7208    ],
       [  2.        ,  31.        ,  13.        ],
       [  3.        ,   4.        ,  27.9       ],
       [  3.        ,  31.        ,   7.8542    ],
       [  3.        ,  19.        ,   7.8958    ],
       [  3.        ,  22.        ,   7.75      ],
       [  1.        ,  40.60645422,  30.6958    ],
       [  3.        ,  23.        ,   7.55      ],
       [  3.        ,  18.        ,   8.05      ],
       [  3.        ,  27.        ,  14.4542    ],
       [  1.        ,  28.        ,  35.5       ],
       [  3.        ,  28.5       ,   7.75      ],
       [  1.        ,  30.        ,  31.        ],
       [  3.        ,  30.4       ,   7.8958    ],
       [  2.        ,  21.        ,  73.5       ],
       [  3.        ,  29.        ,   7.0458    ],
       [  3.        ,  39.3       ,   8.05      ],
       [  3.        ,  28.5       ,   7.75      ],
       [  3.        ,  45.        ,  14.4542    ],
       [  3.        ,  16.        ,  34.375     ],
       [  3.        ,  19.        ,   8.1583    ],
       [  3.        ,  23.        ,   9.225     ],
       [  3.        ,  24.        ,   7.05      ],
       [  1.        ,  58.        , 113.275     ],
       [  3.        ,   5.        ,  19.2583    ],
       [  1.        ,  52.        ,  93.5       ],
       [  3.        ,  40.        ,  27.9       ],
       [  1.        ,  11.        , 120.        ],
       [  3.        ,  65.        ,   7.75      ],
       [  1.        ,  18.        ,  79.65      ],
       [  2.        ,  32.        ,  10.5       ],
       [  1.        ,  50.        , 247.5208    ],
       [  2.        ,  35.        ,  21.        ],
       [  3.        ,  19.        ,   7.8792    ],
       [  3.        ,  21.        ,   7.775     ],
       [  2.        ,  13.        ,  19.5       ],
       [  2.        ,  28.        ,  26.        ],
       [  1.        ,  47.77686448,  25.925     ],
       [  3.        ,  28.5       ,   7.75      ],
       [  2.        ,  57.        ,  10.5       ],
       [  2.        ,  21.        ,  73.5       ],
       [  3.        ,  29.        ,   7.875     ],
       [  3.        ,  17.        ,   7.2292    ],
       [  1.        ,  52.        ,  78.2667    ],
       [  2.        ,  26.        ,  26.        ],
       [  1.        ,  18.        , 262.375     ],
       [  1.        ,  26.        ,  30.        ],
       [  1.        ,  39.        ,  83.1583    ],
       [  3.        ,  23.        ,   7.8542    ],
       [  3.        ,  36.        ,  15.55      ],
       [  3.        ,  30.5       ,   7.75      ],
       [  1.        ,  22.        ,  49.5       ],
       [  2.        ,  38.        ,  13.        ],
       [  3.        ,  41.        ,  20.2125    ],
       [  3.        ,  16.        ,  39.6875    ],
       [  2.        ,  29.        ,  10.5       ],
       [  1.        ,  40.        , 134.5       ],
       [  3.        ,  23.93028323,   7.7375    ],
       [  1.        ,  56.        ,  30.6958    ],
       [  1.        ,  71.        ,  49.5042    ],
       [  1.        ,  31.        , 113.275     ],
       [  1.        ,  30.        ,  56.9292    ],
       [  1.        ,  38.        ,   0.        ],
       [  3.        ,  26.8       ,   7.25      ],
       [  3.        ,   9.        ,  20.525     ],
       [  3.        ,   9.        ,  31.275     ],
       [  1.        ,  61.        ,  32.3208    ],
       [  3.        ,  21.81751392,   7.7292    ],
       [  3.        ,  30.4       ,   7.8958    ],
       [  3.        ,  28.        ,   7.8542    ],
       [  1.        ,  48.        ,  52.        ],
       [  3.        ,  45.        ,   8.05      ],
       [  2.        ,  36.        ,  13.        ],
       [  3.        ,  27.        ,   7.8958    ],
       [  1.        ,  64.        ,  26.        ],
       [  3.        ,  35.        ,   7.125     ],
       [  1.        ,  19.        ,  91.0792    ],
       [  3.        ,  38.        ,   7.05      ],
       [  3.        ,  30.5       ,   8.05      ],
       [  3.        ,  25.        ,   7.775     ],
       [  2.        ,  40.        ,  39.        ],
       [  1.        ,  47.        ,  38.5       ],
       [  3.        ,  30.        ,   9.5       ],
       [  1.        ,  40.        ,  31.        ],
       [  1.        ,  36.        ,  52.        ],
       [  3.        ,  20.5       ,   7.25      ],
       [  1.        ,  49.        ,  89.1042    ],
       [  1.        ,  36.        ,  26.2875    ],
       [  1.        ,  24.5580797 , 221.7792    ],
       [  3.        ,  20.        ,   9.8458    ],
       [  1.        ,  71.        ,  34.6542    ],
       [  2.        ,  36.        ,  12.875     ],
       [  2.        ,  22.        ,  29.        ],
       [  3.        ,  48.        ,  34.375     ],
       [  2.        ,  23.        ,  11.5       ],
       [  1.        ,  32.        ,  76.2917    ],
       [  1.        ,  63.        ,  77.9583    ],
       [  2.        ,   0.83      ,  29.        ],
       [  3.        ,  25.        ,   7.25      ],
       [  1.        ,  35.        ,  26.55      ],
       [  1.        ,  49.        ,  25.9292    ],
       [  1.        ,  24.        ,  79.2       ],
       [  3.        ,  17.        ,  14.4583    ],
       [  3.        ,  21.        ,   8.05      ],
       [  3.        ,  33.        ,   7.8792    ],
       [  3.        ,  29.        ,  15.2458    ],
       [  2.        ,  37.8       ,   0.        ],
       [  3.        ,   5.        ,  12.475     ],
       [  1.        ,  49.        ,  56.9292    ],
       [  3.        ,  15.        ,  14.4542    ],
       [  1.        ,  35.        , 110.8833    ],
       [  3.        ,  29.        ,   7.775     ],
       [  3.        ,  42.        ,   7.55      ],
       [  3.        ,  18.        ,  17.8       ],
       [  3.        ,  21.        ,   8.4333    ],
       [  2.        ,  44.        ,  26.        ],
       [  2.        ,  28.        ,  13.        ],
       [  2.        ,  37.        ,  26.        ],
       [  3.        ,  39.        ,  29.125     ],
       [  2.        ,  34.        ,  32.5       ],
       [  2.        ,  30.        ,  13.        ],
       [  2.        ,  66.        ,  10.5       ],
       [  1.        ,  58.        , 146.5208    ],
       [  3.        ,  43.        ,   8.05      ],
       [  3.        ,  23.99760192,   8.7125    ],
       [  3.        ,  24.        ,   7.4958    ],
       [  3.        ,  18.        ,   7.7958    ],
       [  3.        ,  25.75      ,  24.15      ],
       [  3.        ,  39.3       ,   8.05      ],
       [  3.        ,  22.5       ,   7.05      ],
       [  3.        ,  29.5       ,  56.4958    ],
       [  3.        ,  24.4       ,   7.7875    ],
       [  2.        ,  36.        ,  26.        ],
       [  3.        ,  32.        ,  15.5       ],
       [  3.        ,  23.5       ,   7.2292    ],
       [  1.        ,  55.4       ,  26.55      ],
       [  2.        ,  39.        ,  13.        ],
       [  1.        ,  28.        ,  82.1708    ],
       [  3.        ,  24.35666027,   8.4583    ],
       [  1.        ,  65.        ,  61.9792    ],
       [  2.        ,  23.        ,  10.5       ],
       [  1.        ,  53.99973341,  51.8625    ],
       [  3.        ,  22.        ,   7.8958    ],
       [  3.        ,  35.        ,   7.05      ],
       [  1.        ,  23.        ,  63.3583    ],
       [  2.        ,  18.        ,  13.        ],
       [  1.        ,  36.        ,  26.3875    ],
       [  3.        ,   9.        ,  15.2458    ],
       [  3.        ,  17.        ,   7.125     ],
       [  3.        ,  29.5       ,   7.225     ],
       [  3.        ,  38.        ,  31.3875    ],
       [  2.        ,  17.        ,  10.5       ],
       [  3.        ,   4.        ,  16.7       ],
       [  1.        ,  45.5       ,  28.5       ],
       [  2.        ,  23.        ,  13.        ],
       [  3.        ,  32.        ,   7.925     ],
       [  3.        ,  26.        ,   7.8542    ],
       [  3.        ,   6.        ,  31.275     ],
       [  1.        ,  24.        , 247.5208    ],
       [  1.        ,  45.        ,  26.55      ],
       [  2.        ,  29.        ,  27.7208    ],
       [  3.        ,  30.4       ,   7.8958    ],
       [  1.        ,  50.5       ,  35.5       ],
       [  2.        ,  42.        ,  13.        ],
       [  3.        ,  36.        ,  24.15      ],
       [  2.        ,  33.        ,  12.275     ],
       [  3.        ,  17.        ,   7.0542    ],
       [  3.        ,  29.        ,   9.5       ],
       [  2.        ,  50.        ,  26.        ],
       [  1.        ,  35.        ,  90.        ],
       [  1.        ,  38.        , 227.525     ],
       [  2.        ,  34.        ,  13.        ],
       [  1.        ,  17.        ,  57.        ],
       [  3.        ,  11.        ,  31.275     ],
       [  3.        ,  61.        ,   6.2375    ],
       [  3.        ,  30.        ,   8.6625    ],
       [  2.        ,   7.        ,  26.25      ],
       [  3.        ,  63.        ,   9.5875    ],
       [  3.        ,  20.        ,   7.2292    ],
       [  3.        ,  19.70662149,  22.3583    ],
       [  3.        ,  29.        ,   9.4833    ],
       [  1.        ,  36.        , 120.        ],
       [  3.        ,  17.        ,  14.4583    ],
       [  3.        ,  50.        ,   8.05      ],
       [  1.        ,  27.        , 211.5       ],
       [  3.        ,  30.        ,   7.25      ],
       [  1.        ,  33.        ,  90.        ],
       [  3.        ,  26.29642273,   7.725     ],
       [  3.        ,  16.2       ,  25.4667    ],
       [  3.        ,   2.        ,  21.075     ],
       [  2.        ,  25.        ,  30.        ],
       [  1.        ,  51.        ,  61.3792    ],
       [  2.        ,  25.        ,  26.        ],
       [  3.        ,  26.8       ,   7.25      ],
       [  3.        ,  30.4       ,   7.8958    ],
       [  2.        ,  24.        ,  13.        ],
       [  3.        ,  18.        ,  20.2125    ],
       [  1.        ,  38.        ,  30.5       ],
       [  3.        ,  25.        ,   7.05      ],
       [  2.        ,  24.        ,  14.5       ],
       [  3.        ,  22.        ,   7.5208    ],
       [  1.        ,   0.92      , 151.55      ],
       [  2.        ,  24.        ,  26.        ],
       [  3.        ,  26.        ,   7.925     ],
       [  2.        ,  34.        ,  21.        ],
       [  1.        ,  21.        , 262.375     ],
       [  3.        ,  28.5       ,   7.75      ],
       [  3.        ,  21.625     ,   7.2292    ],
       [  3.        ,  25.2       ,   8.6625    ],
       [  3.        ,  22.        ,   7.775     ],
       [  1.        ,  62.        ,  80.        ],
       [  3.        ,  18.        ,   9.8417    ],
       [  1.        ,  42.        , 227.525     ],
       [  2.        ,  57.        ,  12.35      ],
       [  3.        ,  19.        ,   0.        ],
       [  2.        ,  42.        ,  26.        ],
       [  3.        ,  29.5       ,   7.225     ],
       [  3.        ,  20.        ,   8.6625    ],
       [  3.        ,  34.5       ,   6.4375    ],
       [  3.        ,  28.        ,   9.5       ],
       [  3.        ,  39.3       ,   8.05      ],
       [  3.        ,  23.        ,   7.8958    ],
       [  3.        ,  22.        ,   7.25      ],
       [  1.        ,  52.        ,  30.5       ],
       [  3.        ,  30.        ,  12.475     ],
       [  2.        ,  36.5       ,  26.        ],
       [  3.        ,  28.5       ,   7.75      ],
       [  3.        ,  22.        ,   7.2292    ],
       [  1.        ,  50.        , 133.65      ],
       [  3.        ,  27.        ,   6.975     ],
       [  3.        ,  22.        ,   8.05      ],
       [  1.        ,  51.        ,  77.9583    ],
       [  2.        ,  36.        ,  10.5       ],
       [  2.        ,  29.        ,  26.        ],
       [  1.        ,  22.        , 151.55      ],
       [  1.        ,  50.        , 106.425     ],
       [  2.        ,  40.        ,  13.        ],
       [  3.        ,  27.        ,   8.6625    ],
       [  1.        ,  39.5       ,   0.        ],
       [  1.        ,  65.        ,  26.55      ],
       [  3.        ,  17.        ,   8.6625    ],
       [  1.        ,  28.        ,  26.55      ]])

In [34]:
pd.DataFrame(X_test_knn,columns=X_train.columns)

     Pclass   Age     Fare
0       3.0  29.0  15.2458
1       2.0  31.0  10.5000
2       3.0  20.0   7.9250
3       2.0   6.0  33.0000
4       3.0  14.0  11.2417
..      ...   ...      ...
263     3.0  27.0   8.6625
264     1.0  39.5   0.0000
265     1.0  65.0  26.5500
266     3.0  17.0   8.6625
267     1.0  28.0  26.5500

[268 rows x 3 columns]

In [35]:
lr=LogisticRegression()
lr.fit(X_train_knn,y_train)

LogisticRegression()

In [36]:
y_pred=lr.predict(X_test_knn)

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test,y_pred)

0.7201492537313433

 # SImpleImputer

In [39]:
si=SimpleImputer()
X_train_si=si.fit_transform(X_train)
X_test_si=si.transform(X_test)

In [40]:
X_train_si

array([[  1.        ,   4.        ,  81.8583    ],
       [  3.        ,  29.25635271,   7.8958    ],
       [  3.        ,   1.        ,  11.1333    ],
       ...,
       [  3.        ,  41.        ,  14.1083    ],
       [  1.        ,  14.        , 120.        ],
       [  1.        ,  21.        ,  77.2875    ]])

In [41]:
lr1=LogisticRegression()
lr1.fit(X_train_si,y_train)

LogisticRegression()

In [42]:
y_pred1=lr1.predict(X_test_si)
accuracy_score(y_test,y_pred1)

0.7238805970149254