In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [13]:
wine=load_wine()

In [14]:
df=pd.DataFrame(wine.data)

In [15]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [16]:
df.columns=wine.feature_names

In [17]:
df['target']=wine.target

In [18]:
df.head()

   alcohol  malic_acid   ash  alcalinity_of_ash  ...   hue  od280/od315_of_diluted_wines  proline  target
0    14.23        1.71  2.43               15.6  ...  1.04                          3.92   1065.0       0
1    13.20        1.78  2.14               11.2  ...  1.05                          3.40   1050.0       0
2    13.16        2.36  2.67               18.6  ...  1.03                          3.17   1185.0       0
3    14.37        1.95  2.50               16.8  ...  0.86                          3.45   1480.0       0
4    13.24        2.59  2.87               21.0  ...  1.04                          2.93    735.0       0

[5 rows x 14 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [20]:
X=df.iloc[:,0:13]
y=df.iloc[:,13]

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
dr=DecisionTreeClassifier(criterion='gini',max_depth=5)

In [23]:
dr.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [24]:
y_pred=dr.predict(X_test)

In [25]:
accuracy_score(y_pred,y_test)

0.9444444444444444

In [26]:
pd.DataFrame(confusion_matrix(y_pred,y_test))

    0   1  2
0  13   0  1
1   1  14  0
2   0   0  7

# Features importance

In [27]:
for importance,name in sorted(zip(dr.feature_importances_,X_train.columns),reverse=True):
    print(name,importance)

flavanoids 0.41105325641668755
color_intensity 0.3849342414127968
proline 0.16407537316792392
ash 0.020942061700526718
alcohol 0.01899506730206504
total_phenols 0.0
proanthocyanins 0.0
od280/od315_of_diluted_wines 0.0
nonflavanoid_phenols 0.0
malic_acid 0.0
magnesium 0.0
hue 0.0
alcalinity_of_ash 0.0