In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [2]:
dia=load_diabetes()

In [3]:
df=pd.DataFrame(dia.data,columns=dia.feature_names)

In [4]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [5]:
df['target']=dia.target

In [6]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:10],df.iloc[:,-1],test_size=0.2,random_state=42)

In [8]:
lr=LinearRegression()
kn=KNeighborsRegressor()
dr=DecisionTreeRegressor()

In [9]:
lr.fit(X_train,y_train)
kn.fit(X_train,y_train)
dr.fit(X_train,y_train)

DecisionTreeRegressor()

In [10]:
y_pred1=lr.predict(X_test)
y_pred2=kn.predict(X_test)
y_pred3=dr.predict(X_test)

In [11]:
print("R2 Score of Lr",r2_score(y_test,y_pred1))
print("R2 Score of KNN",r2_score(y_test,y_pred2))
print("R2 Score of DR",r2_score(y_test,y_pred3))

R2 Score of Lr 0.4526027629719197
R2 Score of KNN 0.43016439526042805
R2 Score of DR 0.009499826767248143

In [12]:
from sklearn.ensemble import BaggingRegressor

In [13]:
bg=BaggingRegressor(random_state=1)
bg.fit(X_train,y_train)

BaggingRegressor(random_state=1)

In [14]:
y_bg=bg.predict(X_test)

In [15]:
r2_score(y_test,y_bg)

0.38598910039540923

In [16]:
print("Training Coefficient of r2 : %.3f"%bg.score(X_train,y_train))
print("Test Coefficient of r2 : %.3f"%bg.score(X_test,y_test))

Training Coefficient of r2 : 0.895
Test Coefficient of r2 : 0.386

In [17]:
%%time

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?

In [18]:
import streamlit as st

In [19]:
st.title("Bagging")

2026-01-06 19:41:12.595 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-01-06 19:41:13.471
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\91886\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-01-06 19:41:13.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()